version: '3'
services:
  web:
    build: ./web
    image: kegbot-api
    ports:
    - "3000:3000"
    command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--", "python", "app.py"]
    volumes:
    - ./web:/app
    links:
    - db
  db:
    build: ./db
    image: kegbot-db
    ports:
    - "5555:5432"
    volumes:
    - ./db/data:/var/lib/postgresql/data
